# Tensor Operations with PyTorch

In [1]:
# Basic Imports
import torch
import torch.nn as nn

## Tensor Creation

### Direct Initialization

In [2]:
# Create a tensor from a list
a = torch.tensor([1, 2, 3])
print(f"a = \n{a}")
b = torch.tensor([[1, 2], [3, 4]])
print(f"b = \n{b}")

a = 
tensor([1, 2, 3])
b = 
tensor([[1, 2],
        [3, 4]])


In [3]:
# Create a tensor of zeros
zeros = torch.zeros((2, 3))
print(f"zeros = \n{zeros}")

zeros = 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Create a tensor of ones
ones = torch.ones((2, 3))
print(f"ones = \n{ones}")

ones = 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Random Initialization

In [5]:
# Create a tensor with random values between 0 and 1
rand_tensor = torch.rand((2, 3))
print(f"rand_tensor = \n{rand_tensor}")

rand_tensor = 
tensor([[0.6607, 0.8999, 0.7682],
        [0.5018, 0.4473, 0.6859]])


In [6]:
# Create a tensor with random values from normal distribution
randn_tensor = torch.randn((2, 3))
print(f"randn_tensor = \n{randn_tensor}")

randn_tensor = 
tensor([[-1.6695,  2.9364,  1.0581],
        [-0.8060,  0.6887,  1.2288]])


## Addition and Subtraction

In [7]:
A = torch.tensor([1, 2, 3, 4])
B = torch.tensor([3, 2, 1, 4])

add1 = torch.add(A, B)
print(f"add1 = {add1}")

add2 = A + B
print(f"add2 = {add2}")

sub1 = torch.sub(A, B)
print(f"sub1 = {sub1}")

sub2 = A - B
print(f"sub2 = {sub2}")

add1 = tensor([4, 4, 4, 8])
add2 = tensor([4, 4, 4, 8])
sub1 = tensor([-2,  0,  2,  0])
sub2 = tensor([-2,  0,  2,  0])


## Multiplication

In [8]:
# Element-wise Multiplication

# Scalar Multiplication (Scalar -> 0D tensor)
a = torch.tensor(3.0)
b = torch.tensor(2.0)
result = a * b
print(f"a * b = {result}")

c = torch.tensor([1, 2, 3])
d = torch.tensor([5, 6, 7])
result = c * d
print(f"c * d = {result}")

e = torch.tensor([[2, 3, 4], [7, 3, 4]])
f = torch.tensor([[5, 1, 2], [3, 2, 0]])
result = e * f
print(f"e * f = {result}")

a * b = 6.0
c * d = tensor([ 5, 12, 21])
e * f = tensor([[10,  3,  8],
        [21,  6,  0]])


In [9]:
# Broadcasting -> Multiplying a tensor by a scalar
a = torch.tensor([[2, 3], [4, 7]])
b = 2
result = a * b
print(f"a * b = {result}")

a * b = tensor([[ 4,  6],
        [ 8, 14]])


In [10]:
# Vector-Vector Multiplication (Dot Product between two 1D tensors)
vector1 = torch.tensor([1, 2, 3, 4])
vector2 = torch.tensor([3, 4, 2, 6])

result1 = torch.dot(vector1, vector2)
print(f"result1 = {result1}")

result2 = torch.matmul(vector1, vector2)
print(f"result2 = {result2}")

result1 = 41
result2 = 41


In [11]:
# Matrix-Vector Multiplication (2D tensor with 1D tensor) => Output is a Vector
matrix = torch.tensor([[1, 2], [3, 4]])
vector = torch.tensor([5, 6])
result = torch.matmul(matrix, vector)
print(f"result = {result}")

result = tensor([17, 39])


In [12]:
# Matrix-Matrix Multiplication
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[2, 5], [3, 7]])
result1 = torch.matmul(matrix1, matrix2)
print(f"result1 = {result1}")

result2 = torch.mm(matrix1, matrix2)
print(f"result2 = {result2}")

result1 = tensor([[ 8, 19],
        [18, 43]])
result2 = tensor([[ 8, 19],
        [18, 43]])


## Exponentiation

In [13]:
A = torch.tensor([1, 2, 3, 4])
B = torch.tensor([[2, 3], [4, 7]])

result = 1 / (1 + torch.exp(A))
print(f"result = {result}")
result = 1 / (1 + torch.exp(B))
print(f"result = {result}")

result = tensor([0.2689, 0.1192, 0.0474, 0.0180])
result = tensor([[0.1192, 0.0474],
        [0.0180, 0.0009]])


## Clamp

In [14]:
a = torch.tensor([1, 3, 5, 7, 10, 13, 15])

# Clamp values between 2 and 11
result = torch.clamp(a, min=2, max=11)
print(f"result = {result}")

result = tensor([ 2,  3,  5,  7, 10, 11, 11])


## Max and Min

In [15]:
a = torch.tensor([3, 7, 1, 9, 4])

# Find maximum and minimum values
max_val = torch.max(a)
min_val = torch.min(a)

print(f"max_val = {max_val}")
print(f"min_val = {min_val}")

max_val = 9
min_val = 1


## Reshaping

In [16]:
a = torch.arange(1, 13)  # 1D tensor with values from 1 to 12

reshaped_tensor1 = a.view((2, 6))  # Reshape it to 2 x 6 matrix
print(f"reshaped_tensor1 = {reshaped_tensor1}")

reshaped_tensor2 = a.reshape((4, 3))  # Reshape it to 4 x 3 matrix
print(f"reshaped_tensor2 = {reshaped_tensor2}")

reshaped_tensor1 = tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
reshaped_tensor2 = tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


## Concatenation

In [17]:
a = torch.tensor([[2, 3], [4, 5]])
b = torch.tensor([[5, 9]])

# Concat along dimension 0
concated_tensor = torch.cat((a, b), dim=0)
print(f"concated_tensor = \n{concated_tensor}")

concated_tensor = 
tensor([[2, 3],
        [4, 5],
        [5, 9]])


## Summation

In [18]:
tensor = torch.tensor([[1, 2], [3, 4]])

sum_ = torch.sum(tensor)
print(f"Sum of all elements = {sum_}")

Sum of all elements = 10
