# Layers in PyTorch

In [1]:
# Basic Imports
import torch
import torch.nn as nn

RANDOM_SEED = 42

### Linear Layer

- Input tensor x has a shape of (batch_size, input_features)
    1. batch_size -> no of samples in input batch
    2. input_features -> no of features in each sample
- Weight matrix has a shape of (output_features, input_features)
    1. output_features -> no of neurons in the layer
    2. Each row of weight matrix corresponds to weights associated with one neuron in the layer
    3. Each column of weight matrix corresponds to weights associated with one input feature
- Bias has a shape of (output_features,)
    1. One bias value for each neuron in the layer
- Output has a shape of (batch_size, output_features)
    1. ```outputs = inputs.mm(weights.t()) + bias```

In [2]:
torch.manual_seed(RANDOM_SEED)

# batch_size = 4, input_features = 3
inputs = torch.rand((4, 3))
print(f"inputs = \n{inputs}")

linear_layer = nn.Linear(in_features=3, out_features=2, bias=True)

outputs = linear_layer(inputs)
print(f"outputs = \n{outputs}")
print(f"outputs.shape = \n{outputs.shape}")

inputs = 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
outputs = 
tensor([[0.2849, 0.5152],
        [0.3375, 0.2940],
        [0.1639, 0.5598],
        [0.0256, 0.6029]], grad_fn=<AddmmBackward0>)
outputs.shape = 
torch.Size([4, 2])


### Convolutional Layer

#### Output Dimension = [(Input Dimension + 2 * Padding - Kernel Size) / Stride] + 1

## Custom Layers

### Custom Linear Layer

In [3]:
class CustomLinear(nn.Module):
  def __init__(self, in_features, out_features, bias):
    super(CustomLinear, self).__init__()

    # Define Linear layer parameters
    self.in_features = in_features
    self.out_features = out_features
    self.bias = bias

    # Initialize weights and biases
    self.weights = nn.Parameter(torch.randn(self.out_features, self.in_features))
    if self.bias:
      self.biases = nn.Parameter(torch.randn(self.out_features))

  def forward(self, x):
    if self.bias:
      return x.mm(self.weights.t()) + self.biases
    else:
      return x.mm(self.weights.t())

In [4]:
torch.manual_seed(RANDOM_SEED)
# batch_size = 4, input_features = 3
inputs = torch.rand((4, 3))
print(f"inputs = \n{inputs}")

linear_layer = CustomLinear(in_features=3, out_features=2, bias=True)

outputs = linear_layer(inputs)
print(f"outputs = \n{outputs}")
print(f"outputs.shape = \n{outputs.shape}")

inputs = 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
outputs = 
tensor([[ 2.6515, -0.6546],
        [ 3.2569, -0.7381],
        [ 1.6048, -0.4353],
        [ 1.0822, -0.6739]], grad_fn=<AddBackward0>)
outputs.shape = 
torch.Size([4, 2])


### Custom Conv2D Layer

In [5]:
class CustomConv2D(nn.Module):
  def __init__(self, in_channels, out_channels, kernel_size, stride, padding):
    super(CustomConv2D, self).__init__()

    # Define Convolutional layer parameters
    self.in_channels = in_channels
    self.out_channels = out_channels
    self.kernel_size = kernel_size
    self.stride = stride
    self.padding = padding

    # Initialize Convolutional weights and biases
    self.weights = nn.Parameter(torch.randn(out_channels, in_channels, kernel_size, kernel_size))
    self.bias = nn.Parameter(torch.randn(out_channels))

    def forward(self, x):
      # Get the dimensions of the input tensor
      batch_size, in_channels, height, width = x.size()

      # Calculate dimensions after applying padding
      padded_height = height + (padding * 2)
      padded_width = width + (padding * 2)

      # Calculate dimensions after applying stride
      output_height = (padded_height - self.kernel_size) // self.stride + 1
      output_width = (padded_width - self.kernel_size) // self.stride + 1

      # Initialize output tensor
      output = torch.zeros(batch_size, self.out_channels, output_height, output_width)

      # Perform the convolution operation



